[+] Created owner account  owner_account
[+] Created creator account  creator_owner_account
[+] Created contract /src/build/contracts/EpochLibrary.json
[+] Created contract /src/build/contracts/ConditionStoreManager.json
[+] Initialized contract  /build/contracts/ConditionStoreManager.json
[+] Created condition owner account  condition_owner_account
2019-03-13 12:37:27,807: [3364] m.c.executor:[31mERROR:[0m Exception: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.2.4-py3.6.egg/manticore/core/executor.py", line 454, in run
    if not current_state.execute():
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.2.4-py3.6.egg/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.2.4-py3.6.egg/manticore/platforms/evm.py", line 2368, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.2.4-py3.6.egg/manticore/platforms/evm.py", line 1030, in execute
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.2.4-py3.6.egg/manticore/platforms/evm.py", line 809, in _consume
    enough_gas_solutions = solver.get_all_values(self.constraints, Operators.UGT(self._gas, fee))
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.2.4-py3.6.egg/manticore/core/smtlib/solver.py", line 408, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.2.4-py3.6.egg/manticore/core/smtlib/solver.py", line 306, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError

